### ISSUE TITLE
Podman container on raspian

### ISSUE THREAD

**Issue by foobar092** [liveaverage/docker-powerwall-dashboard#10]
Container never starts, shows the following error:

{"msg":"exec container process `/opt/run.sh`: Exec format error","level":"error","time":"2021-03-27T23:47:46.000050247Z"}

**Comment by liveaverage** [comment]
I'm not currently supporting images on `aarch64` ... I'll open a feature request to support aarch64 specifically, but for now you'll need to run on x86.
