### ISSUE TITLE
Add aarch64 support

### ISSUE THREAD

**Issue by liveaverage** [liveaverage/docker-powerwall-dashboard#11]
**Is your feature request related to a problem? Please describe.**
Issue #10 as reported by @foobar092 

**Describe the solution you'd like**
Add `aarch64` support

**Describe alternatives you've considered**
Only x86 currently supported

**Additional context**

**Comment by natrlhy** [comment]
I'd love to see support for Raspberry Pi OS

**Comment by liveaverage** [comment]
Only targeting `aarch64` at the moment, possibly looking to add 32-bit support. There's a first draft available via:

`docker pull liveaverage/powerwall-dashboard:aarch64`

But if you're running Raspberry Pi OS/Raspbian, it's probably 32-bit unless you're using a beta/test version... This works fine on my Rock64 SBCs. Feel free to review the `multiarch` branch for details on changes, which required use of binaries from influxdb/telegraf vs. repos due to availability for aarch64: https://github.com/liveaverage/docker-powerwall-dashboard/blob/multiarch/Dockerfile

**Comment by liveaverage** [comment]
A quick update that aarch64 builds will be standard moving forward, now available via:

`docker pull liveaverage/powerwall-dashboard:multiarch`

I'll be adding additional workflow steps to publish images to Quay.io and moving multiarch support to the `latest` tag, but for now there's a workflow to handle `linux/amd64` and `linux/arm64`.... I attempted `linux/arm/v7` as a target platform as well, but kept hitting qemu segfaults. If anyone with more interest in 32-bit builds would like to test and submit a PR feel free, but aarch64 will be the only ARM platform supported for now.

https://github.com/liveaverage/docker-powerwall-dashboard/blob/multiarch/.github/workflows/build_images.yml#L63
