### ISSUE TITLE
Backup Options

### ISSUE THREAD

**Issue by natrlhy** [liveaverage/docker-powerwall-dashboard#14]
Do you have any recommended ways to back up all the data that is collected?

Right now I am just stopping the docker image, and backing up everything in my docker directory.

**Comment by liveaverage** [comment]
That's one way to do it, and currently how I backup my data via [duplicity](https://gitlab.com/duplicity/duplicity). You could also use the native backup available from `influxd` for "live" backups without stopping the container: https://docs.influxdata.com/influxdb/v1.8/administration/backup_and_restore/#backup

You can execute that pretty easily from the docker host, though you might want to map an _additional_ volume to your container (perhaps backed by a CIFS/NFS share) to store file-based backups generated by `influxd`:

```console
## Create a directory in the existing LOCAL_INFLUXDB_PATH (where you store influxdb data on your docker host) called "backups"
mkdir /srv/powerwall/influxdb/backups

## The above docker host directory is already mounted in the container at /var/lib/influxdb, so now we can execute the backup
docker exec powerwall-dashboard influxd backup -portable /var/lib/influxdb/backups

## The backup files should be available on your docker host (in my example) at /srv/powerwall/influxdb/backups
ls -lah /srv/powerwall/influxdb/backups
```

If you want to backup any other config files and/or custom dashboards just make sure they're also included in your backup routine/automation.

FYSA influxdb OSS 1.8.4 is what the latest image uses.
