### ISSUE TITLE
Seems there may be an issue with the API's - On new PW firmware

### ISSUE THREAD

**Issue by natrlhy** [liveaverage/docker-powerwall-dashboard#15]
Opened an issue here intially:

https://github.com/rhodesman/teslaPowerDash/issues/27

**Comment by liveaverage** [comment]
This appears related to failure on API auth to create/update a cookie for use/consumption by telegraf, so it'll require some investigation and an update to the `create_cookie` function once complete.

**Comment by liveaverage** [comment]
Ah. Request payload structure changed and the `force_sm_off` parameter is breaking auth ... I'll merge changes and it should be working in a few:

This is working for me (identified by inspecting JSON request payload):
```console
{"username": "customer", "password": "$PASSWORD", "email": "$EMAIL"}
```

This doesn't:
```console
 {"username": "$USERNAME", "password": "$PASSWORD", "email":"$EMAIL", "force_sm_off":false}
```

**Comment by natrlhy** [comment]
I'm using docker, so happy to test any branch that may have been updated. When it's updated, I'm not sure if I should do a docker pull from quay.io or docker hub or if they all update to the same build :)

**Comment by natrlhy** [comment]
Is there a file I can manually modify to get things working again until changes are pushed/committed?

**Comment by tatsu574** [comment]
I got mine running by switching the endpoints in all the conf files over to using IPs. So the files in powerwall.conf and the cookie update script. After that I had to edit every panel in my dashboard to include both URI for data, meaning each panel has 2 queries that are the same other than the URI

Just to note I never had to remove the force_sm_off perameter on the cookie creation script to work.

**Comment by liveaverage** [comment]
@tatsu574 you're correct that should work fine, too. You could also modify the alias, as I ended up doing, to `powerwall` or another SAN listed on the self-signed cert associated with the Backup Gateway. I updated the Grafana dashboard to remove `url` tag filters for each panel. This ensures your dashboard will show historical data pre-API update and newly scraped time series data. Thanks for sharing, and nice work getting yours going again :) 

Just pushed a lot of changes up, including dockerfile cleanup, version bumps for associated binaries (influxdb, telegraf), etc. Pipeline should be running and images should be available soon.

**Comment by tatsu574** [comment]
@liveaverage Thanks for all the work on this, Been running it for over a year. Didn't even occur to me to look at the SAN in the cert. Looks like I'll be updating my instance tonight.

**Comment by liveaverage** [comment]
Thanks for the initiative on getting your instance tested/sorted! Images with the fix are now available on Dockerhub and quay.io, and they shouldn't introduce any breaking changes.... if you're already referencing the `latest` tag from Dockerhub it should auto-pull on container restart... and if you're using the dashboard provided in the repo it now includes *all* influxdb http urls, so any previous/current historical data should appear. 

In the near future I'll be switching this to a `ubi8-minimal` image to further limit the image size and possible security vulnerabilities... layer consolidation did shave off ~100MB+ (compressed) but should be able to get it a bit smaller. Closing this out for now.
