### ISSUE TITLE
differences from Tesla App

### ISSUE THREAD

**Issue by mihailescu2m** [liveaverage/docker-powerwall-dashboard#4]
1. battery % - soe/percentage is shown differently because Tesla "hides" 5% of battery.
So when soe is 10%, tesla app will show 5%, when soe is 100%, tesla app will show 100% :)
so you need (percent - 5)/0.95 :)

2. singe values kWh are wrong - e.g. for solar during the day i've seen how, after 1h, values jump in value very much, then as the time passes, they actually decrease a bit (while the Tesla App shows the correct value increasing constantly). May have to do with how grafana computes stuff. E.g. I am calculating "To Powerwall" as:
MEAN(battery_instant_power) WHERE battery_instant_power < 0 GROUP BY (1h)
and I get values > 16kWh, physically impossible :)

Anyone else have seen these issues?

EDIT: I am trying to make the results as close as possible to the Powerwall app numbers ... which is proving not so easy :D

This is what I got so far:

![Capture](https://user-images.githubusercontent.com/4421731/70500788-479b4f00-1b6c-11ea-86ce-ab2bce601e92.JPG)

**Comment by liveaverage** [comment]
Hi @mihailescu2m and sorry for the delay -- for some reason I wasn't receiving notifications for issues in this repo. If you haven't already, I would also check on these issues with the maintainer for the repo this image is based on: https://github.com/rhodesman/teslaPowerDash 

I'd agree RE: item 1 -- there is a built-in reserve so calculations would be off without accommodating for -5%. RE: item 2, if you're attempting to match 1:1 with app values it might be worth querying the non-local API from Tesla: https://www.teslaapi.io/powerwalls/commands -- not much in terms of documentation but you may be able to query/store/display the same historical data. https://www.reddit.com/r/teslamotors/comments/h9rohn/powerwall_api_unofficial_for_historical_energy/
