### ISSUE TITLE
Import from existing TeslaPowerDash?

### ISSUE THREAD

**Issue by Nakatomi2010** [liveaverage/docker-powerwall-dashboard#5]
So, I got the original PowerDash up and running, but the middleware piece has never behaved properly.  I'd like to try shifting to this one, but don't want to lose my 6 months of data from using the original PowerDash.

Is there an export/import function for going from the non docker, to this docker one?

I'm not opposed to just nuking the Pi and starting over, I'd just like to preserve as much data as possible in the cut over.

**Comment by liveaverage** [comment]
Sorry for the delay on reply -- Github wasn't notifying me of new issues! As for time series data migration, it should be pretty easy. Stop your existing deployment and copy the contents of your existing `influxdb` data dir to a *new* destination (to ensure nothing unexpected happens to current trend data). Reference that location as your `LOCAL_INFLUXDB_PATH` before launching the container image and you should be good to go!

**Comment by liveaverage** [comment]
Closing issue, and including note from other conversation(s):

assuming same data structure from a previous deployment you should be able to preseed the influxdb/data with your prexisting data. Reference the proper hostpath dir (at the toplevel for influxdb) after preseeding. The same applies if you've customized any dashboards... just reference the proper hostpath when establishing the volume:
```
        -v ${LOCAL_INFLUXDB_PATH}:/var/lib/influxdb:z \
        -v ${LOCAL_GRAFANA_PATH}:/var/lib/grafana:z \
```
