### ISSUE TITLE
Unauthorized access to quay.io/liveaverage/powerwall-dashboard

### ISSUE THREAD

**Issue by karllmitchell** [liveaverage/docker-powerwall-dashboard#6]
From what I can tell, I followed your instructions precisely.  However, the docker did not initialize.  Any idea what's up?

Trying to pull docker.io/liveaverage/powerwall-dashboard...
Getting image source signatures
Copying blob 337640aebf48 skipped: already exists  
Copying blob 524b0c1e57f8 skipped: already exists  
Copying blob f019e12b35c4 done  
Copying blob f9958570a0a2 done  
Copying blob a5e88d2bb40f done  
Copying blob dd9e67998bc4 done  
Copying blob fa5309fbfd5e done  
Copying blob ddf1e7e0db53 done  
Copying blob 45296ca1b695 done  
Copying blob 053210b966e0 done  
Copying config de9a596216 done  
Writing manifest to image destination
Storing signatures
  invalid argument
Trying to pull quay.io/liveaverage/powerwall-dashboard...
  unauthorized: access to the requested resource is not authorized
Error: unable to pull liveaverage/powerwall-dashboard: 2 errors occurred:
	* Error committing the finished image: error adding layer with blob "sha256:f019e12b35c45470df49246e0aba4efc6f7209bddf06c9d65e10541b19c145d9": error creating layer with ID "e3ab964ba05b37fa581edcccb7f19c6c04a0eff84a302981faa49b07b0324f62": invalid argument
	* Error initializing source docker://quay.io/liveaverage/powerwall-dashboard:latest: Error reading manifest latest in quay.io/liveaverage/powerwall-dashboard: unauthorized: access to the requested resource is not authorized

**Comment by liveaverage** [comment]
Can you share your exact command `docker` command? Seems like the issue is related to pulling from quay.io (vs. docker.io). I'm not yet hosting on quay.io, though I'll likely move it there.

**Comment by liveaverage** [comment]
Issue resolved. Image repo has been established on Quay.io to avoid docker hub limits: https://quay.io/repository/liveaverage/powerwall-dashboard?tab=tags

```
docker pull quay.io/liveaverage/powerwall-dashboard:latest
```
