### ISSUE TITLE
Data Gaps

### ISSUE THREAD

**Issue by natrlhy** [liveaverage/docker-powerwall-dashboard#9]
Hi, I've noticed that there are data gaps and not sure what would be causing it. My system that is running docker desktop is always on and always connected.

Has anyone else seen this? Any fixes?

Today so far:
![image](https://user-images.githubusercontent.com/19696424/112333735-14ed6b00-8c78-11eb-80c3-5577270cd5c4.png)

Yesterday:
![image](https://user-images.githubusercontent.com/19696424/112333615-ff784100-8c77-11eb-8599-58fdbac50132.png)

**Comment by liveaverage** [comment]
Any gaps could be attributed to network connectivity issues associated with your Powerwall/gateway or system running the dashboard container, issues with the docker daemon, etc.  Certainly haven't seen that issue for as long as I've been trending stats against the Powerwall.

Have you attempted to run from a standalone docker host? Is your host hardwired or connected via wifi? Is your Backup Gateway hardwired or connected via wifi?

**Comment by natrlhy** [comment]
Thanks, 

My Tesla Gateway is connected via wifi with a good signal. The Tesla App never seems to have issues.

I was figuring the same and did some tweaking on my Windows 10 system with SSD's, pagefile, etc. Seems to be less freqent now. I normally do all this from Linux as well but just getting the testing done. May move it all to a Raspberry Pi 4 :)

**Comment by liveaverage** [comment]
:+1: Sounds good! Closing for now.

**Comment by natrlhy** [comment]
FYI, even though my TEG had a good WiFi signal, I figured I would hard-wire it since I had Ethernet in my garage. After doing that, no more data gaps! Problem solved!
